name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [ "main" ]   # mainブランチにpushされたら実行

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v4

      - name: Astroをビルド
  uses: withastro/action@v3
  with:
    package-manager: npm

      - name: GitHub Pagesにデプロイ
        uses: actions/deploy-pages@v4
